#!/bin/sh

scan_deps(){
	# This is really hacky but it might just work for most things
	ldd "$1" | tr -d "\t=" | cut -d "(" -f 1 | while read line; do
		case "$line" in
			"not a dynamic executable"*)
				printf "Can't properly read dependencies, this may not work\n"
				break
				;;
			"statically"*)
				# Statically linked, we're done
				break
				;;
			"linux-vdso"*)
				# Skip, provided by kernel
				;;
			*" > "*)
				want_lib "$(printf "%s" "$line" | tr -d "[:space:]" | cut -d ">" -f 1)" "$(printf "%s" "$line" | tr -d "[:space:]" | cut -d ">" -f 2)"
				;;
			*)
				want_lib "$line"
				;;
		esac
	done
}

want_bin(){
	binpath=$(which "$1")
	if [ -z "$binpath" ]; then
		printf "Failed to find binary %s\n" "$1"
		exit 1
	fi

	if [ -x "./$binpath" ]; then
		return 0
	fi

	printf "\tPulling in binary %s\n" "$1"
	mkdir -p "./$(dirname $binpath)"
	cp "$binpath" "./$binpath"

	scan_deps "$binpath"
	return 0
}

want_file(){
	if [ ! -f "$1" ]; then
		printf "No such file %s\n" "$1"
		return 0
	fi

	printf "\tPulling in file %s\n" "$1"
	mkdir -p "./$(dirname $1)"
	cp "$1" "./$1"
	return 0
}

want_lib(){
	case "$1" in
		/*)
			# Direct-copy library
			libpath="$1"
			libname="$(basename "$1")"
			;;
		*)
			# Test-find library
			if [ -n "$2" ]; then
				libpath="$2"
				libname="$1"
			else
				# Need to find library path
				printf "Functionality not yet implemented\n"
				exit 1
			fi
	esac

	if [ -f "./$libpath" ]; then
		return 0
	fi

	printf "\tPulling in library %s\n" "$libname"
	mkdir -p "./$(dirname $libpath)"
	cp "$libpath" "./$libpath"

	scan_deps "$libpath"
	return 0
}

want_module_internal(){
	modinfo=$(grep "$1" "/lib/modules/$(uname -r)/modules.dep" | head -n 1)
	if [ -z "$modinfo" ]; then
		printf "Module %s not found\n" "$1"
		return 1
	fi

	modpath="/lib/modules/$(uname -r)/$(printf "%s" "$modinfo" | cut -d ":" -f 1)"
	moddeps="$(printf "%s" "$modinfo" | cut -d ":" -f 2 | tr " " "\n")"

	if [ -f ".$modpath" ]; then
		return 0
	fi

	printf "\tPulling in module %s\n" "$(basename "$modpath")"

	mkdir -p ".$(dirname $modpath)"
	cp "$modpath" ".$modpath"

	if [ -n "$moddeps" ]; then
		for dep in $moddeps; do
			want_module_internal "$dep:"
		done
	fi
	return 0
}

want_module(){
	printf "$1\n" >> modules
	if [ -n "$2" ]; then
		want_module_internal $2
	else
		want_module_internal $1
	fi
}

want_module_dir(){
	printf "Not yet implemented\n"
	return 1
}

want_dir(){
	case "$1" in
		"/"*)
			break;
			;;
		*)
			printf "Cannot pull in directory %s based on relative paths\n" "$1"
			return 1
			;;
	esac

	printf "\tPulling in directory %s\n" "$1"
	mkdir -p "./$1"
	cp -dr "$1/." "./$1"
}
